# Generated by Django 4.0.3 on 2022-05-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                (
                    "save_count",
                    models.IntegerField(
                        default=0, help_text="Number of times the object has been saved"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        default="LDN", max_length=3
                    ),
                ),
                ("confirmation", models.BooleanField(default=True)),
                ("preparation", models.BooleanField(default=True)),
                ("invoice", models.BooleanField(default=False)),
                ("market_report", models.BooleanField(default=False)),
                ("news_letter", models.BooleanField(default=False)),
                ("credit_note", models.BooleanField(default=False)),
                ("second_selection", models.BooleanField(default=False)),
                ("object_id", models.PositiveIntegerField()),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone", models.CharField(blank=True, max_length=100, null=True)),
                ("mobile", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                "ordering": ["first_name"],
            },
        ),
        migrations.CreateModel(
            name="ContactPosition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                (
                    "save_count",
                    models.IntegerField(
                        default=0, help_text="Number of times the object has been saved"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        default="LDN", max_length=3
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "sync_to_crm",
                    models.BooleanField(
                        default=False,
                        help_text='E.g. do not sync "Finance" positions to CRM',
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactsSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                (
                    "save_count",
                    models.IntegerField(
                        default=0, help_text="Number of times the object has been saved"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        default="LDN", max_length=3
                    ),
                ),
                ("activate_confirmation", models.BooleanField(default=True)),
                ("activate_preparation", models.BooleanField(default=True)),
                ("activate_invoice", models.BooleanField(default=True)),
                ("activate_market_report", models.BooleanField(default=True)),
                ("activate_news_letter", models.BooleanField(default=True)),
                ("activate_credit_note", models.BooleanField(default=True)),
                ("activate_second_selection", models.BooleanField(default=True)),
                (
                    "label_confirmation",
                    models.CharField(default="Confirmation", max_length=100),
                ),
                (
                    "label_preparation",
                    models.CharField(default="Preparation", max_length=100),
                ),
                ("label_invoice", models.CharField(default="Invoice", max_length=100)),
                (
                    "label_market_report",
                    models.CharField(default="Market Report", max_length=100),
                ),
                (
                    "label_news_letter",
                    models.CharField(default="News Letter", max_length=100),
                ),
                (
                    "label_credit_note",
                    models.CharField(default="Credit Note", max_length=100),
                ),
                (
                    "label_second_selection",
                    models.CharField(default="Second Selection", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Contacts Settings",
                "verbose_name_plural": "Contacts Settings",
            },
        ),
        migrations.CreateModel(
            name="EmailRecipientList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                (
                    "save_count",
                    models.IntegerField(
                        default=0, help_text="Number of times the object has been saved"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        default="LDN", max_length=3
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recipients",
                    models.TextField(
                        help_text="List of recipients, separated by commas"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Email Recipient Lists",
            },
        ),
    ]
