# Generated by Django 4.0.4 on 2022-09-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='region',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='save_count',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='contactposition',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactposition',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contactposition',
            name='region',
        ),
        migrations.RemoveField(
            model_name='contactposition',
            name='save_count',
        ),
        migrations.RemoveField(
            model_name='contactposition',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contactposition',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='contactssettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactssettings',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contactssettings',
            name='region',
        ),
        migrations.RemoveField(
            model_name='contactssettings',
            name='save_count',
        ),
        migrations.RemoveField(
            model_name='contactssettings',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contactssettings',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='emailrecipientlist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emailrecipientlist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='emailrecipientlist',
            name='region',
        ),
        migrations.RemoveField(
            model_name='emailrecipientlist',
            name='save_count',
        ),
        migrations.RemoveField(
            model_name='emailrecipientlist',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='emailrecipientlist',
            name='updated_by',
        ),
    ]
